[01]
# Output Control: 0=None, 1=JPG Only, 2=TIFF Only, 3=Both (JPG+TIFF)
output_lights = 3
output_darks = 2
output_flats = 2
output_biases = 2
output_stack = 1

width = 1936
height = 1096
black_level = 0
white_level = 4095
significant_bits = 12

brightness = 0
contrast = 1
gamma = 1

stack_brightness = 0.2
stack_contrast = 16
stack_dehaze = 0.9
stack_gamma = 1
stack_denoise_strength = 0
stack_denoise_size = 0

stack_size = 32

stack_rotate = 180
font_path = /home/length/fonts/RedHatMono-Regular.ttf
font_size = 25
text_color = 255
shadow_color = 0
shadow_width = 2
position = 30,30
timezone_offset_hours = 0
